FROM --platform=linux/x86_64 ubuntu

RUN apt update
RUN apt install -y python3-pip xvfb software-properties-common
RUN add-apt-repository -y ppa:mozillateam/ppa
COPY mozilla-firefox-apt-preferences .
RUN mv mozilla-firefox-apt-preferences /etc/apt/preferences.d/mozilla-firefox
RUN apt install -y firefox

RUN python3 -m pip install --upgrade pip
COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt
RUN webdrivermanager firefox:v0.32.0
